title: The literature review seminar
description: Website for the literature review seminar (offered by Gerit Wagner)
theme: just-the-docs

url: https://just-the-docs.github.io

repository: digital-work-lab/literature-review-seminar

gh_edit_link: true
gh_edit_link_text: 'Edit this page on GitHub'
gh_edit_repository: 'https://github.com/digital-work-lab/literature-review-seminar'
gh_edit_branch: 'main'
gh_edit_view_mode: 'tree'
