title: The open-source project
description: Open-source project (offered by Gerit Wagner)
theme: just-the-docs

url: https://just-the-docs.github.io

repository: digital-work-lab/open-source-project

gh_edit_link: true
gh_edit_link_text: 'Edit this page on GitHub'
gh_edit_repository: 'https://github.com/digital-work-lab/open-source-project'
gh_edit_branch: 'main'
gh_edit_view_mode: 'tree'

callouts:
  warning:
    title: Warning
    color: red
  highlight:
    title: Info
    color: yellow

exclude: ['session_5_presentations']

logo: "/assets/images/open-source-project.png"

aux_links:
  "Feedback":
    - "https://github.com/digital-work-lab/handbook/issues"
